spring.application.name: genesis

server:
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/genesis
    username: root
    password:

  jpa:
    generate-ddl: true
    open-in-view: false